import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "The offical Madwolf store for all your handmade merchandise needs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className}`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
